# Generated by Django 6.0.1 on 2026-02-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_seller_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Buyer'), ('seller', 'Seller')], default='user', max_length=10),
        ),
    ]
