# Generated by Django 6.0.1 on 2026-02-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('estimated_days', models.PositiveIntegerField(default=3)),
            ],
        ),
    ]
