# Generated by Django 6.0.2 on 2026-02-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
