# Generated by Django 6.0.1 on 2026-02-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shippingaddress_order_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
