# Generated by Django 6.0.1 on 2026-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_profile_role_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., XS, S, M, L, XL or enter custom sizes separated by commas', max_length=100, null=True),
        ),
    ]
