# Generated by Django 6.0.1 on 2026-02-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Size selected by buyer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Size purchased by buyer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, help_text='True if review is from verified purchase'),
        ),
        migrations.AddField(
            model_name='review',
            name='order_item',
            field=models.OneToOneField(blank=True, help_text='Reference to the order item being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app.orderitem'),
        ),
    ]
