# Generated by Django 6.0.1 on 2026-02-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_cartitem_selected_size_orderitem_selected_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Baby', 'Baby')], default='All', help_text='Target audience: Men, Women, Kids, Baby, or All', max_length=10),
        ),
    ]
