# Generated by Django 6.0.1 on 2026-02-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_product_seller_category_seller_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
