# Generated by Django 6.0.1 on 2026-02-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_cart_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('All', 'All'), ('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='All', max_length=10),
        ),
    ]
