# Generated by Django 6.0.2 on 2026-03-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_coupon_useraddress_order_coupon_ordertracking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFront',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=150, unique=True)),
                ('store_name', models.CharField(max_length=200)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='store_logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='store_banners/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='seller_username',
            field=models.CharField(blank=True, help_text='Leave blank for a global coupon', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.storefront'),
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to='app.order')),
            ],
        ),
        migrations.CreateModel(
            name='SellerEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_username', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('vendor_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.vendororder')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_items', to='app.vendororder'),
        ),
    ]
